### ISSUE TITLE
Scematics and Board Layout files are missing

### ISSUE THREAD

**Issue by anuejn** [apertus-open-source-cinema/beta-hardware#2]

**Comment by se6astian-pi** [comment]
collect and commit them to github from here: https://wiki.apertus.org/index.php/AXIOM_Beta/AXIOM_Beta_Hardware#Printed_Circuit_Boards

**Comment by davidak** [comment]
@herbertp will do it: https://lab.apertus.org/T827

**Comment by anuejn** [comment]
moved to the lab
